world:
  name: example_room
  ground_color: {r: 0.5, g: 0.5, b: 0.5}

  walls:
    enabled: true
    size: {w: 10, h: 10}
    height: 1.0
    thickness: 0.1
    color: {r: 0.5, g: 0.5, b: 0.5}
    doors: [south]

  spawn:
    pos: {x: 0, y: 0}
    safe_radius: 1.5

  obstacles:
    static:
      - model: box
        pos: {x: 3, y: 3}
        size: {x: 1.0, y: 0.5, z: 0.8}
        color: red

      - model: cylinder
        pos: {x: -2, y: 1}
        radius: 0.3
        height: 0.6
        color: green

      - model: box
        pos: {x: -3, y: -2}
        size: {x: 0.6, y: 0.6, z: 1.0}
        color: blue

    moving:
      - model: box
        pos: {x: 2, y: -2}
        size: {x: 0.4, y: 0.4, z: 0.6}
        color: yellow

    random:
      count: 3
      models: [box, cylinder]
      size_range: [0.3, 0.8]
      seed: 42
